.TH "md__c_o_n_t_r_i_b_u_t_i_n_g" 3 "Sun Jul 25 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_o_n_t_r_i_b_u_t_i_n_g \- Contributing 
We'd love to accept your code patches! However, before we can take them, we have to jump a couple of legal hurdles\&.
.SH "Contributor License Agreements"
.PP
Please fill out either the individual or corporate Contributor License Agreement as appropriate\&.
.PP
.IP "\(bu" 2
If you are an individual writing original source code and you're sure you own the intellectual property, then sign an \fCindividual CLA\fP\&.
.IP "\(bu" 2
If you work for a company that wants to allow you to contribute your work, then sign a \fCcorporate CLA\fP\&.
.PP
.PP
Follow either of the two links above to access the appropriate CLA and instructions for how to sign and return it\&.
.SH "Submitting a Patch"
.PP
.IP "1." 4
Sign the contributors license agreement above\&.
.IP "2." 4
Decide which code you want to submit\&. A submission should be a set of changes that addresses one issue in the \fCissue tracker\fP\&. Please don't mix more than one logical change per submission, because it makes the history hard to follow\&. If you want to make a change (e\&.g\&. add a sample or feature) that doesn't have a corresponding issue in the issue tracker, please create one\&.
.IP "3." 4
\fBSubmitting\fP: When you are ready to submit, send us a Pull Request\&. Be sure to include the issue number you fixed and the name you used to sign the CLA\&.
.PP
.SH "Writing Code"
.PP
If your contribution contains code, please make sure that it follows \fCthe style guide\fP\&. Otherwise we will have to ask you to make changes, and that's no fun for anyone\&. 
